# Generated by Django 2.0.3 on 2019-04-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.SmallIntegerField()),
                ('projector_available', models.BooleanField(default=False)),
                ('air_conditioned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=64)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_room_manager.Room')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('room', 'date')},
        ),
    ]
